# Generated by Django 3.1 on 2022-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('iname', models.CharField(max_length=30)),
                ('assignment1', models.IntegerField()),
                ('assignment2', models.IntegerField()),
                ('assignment3', models.IntegerField()),
            ],
        ),
    ]
